name: sync index.html from hol_to_ics_web.html

on:
  push:
    paths:
      - hol_to_ics_web.html
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate index.html
        run: cp hol_to_ics_web.html index.html
